name: "Run CI"
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-ci:
    name: CI

    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build and Test
        run: |
          cd TaskCanvasManager
          dotnet build
          cd ../TaskCanvasManager.Test
          dotnet build
          dotnet test
